Master:
  ServiceType: NodePort
  NodePort: 30001
  InstallPlugins:
    - kubernetes:1.1
    - workflow-aggregator:2.5
    - workflow-job:2.15
    - credentials-binding:1.13
    - git:3.6.4
    - blueocean:1.3.5